In [12]:
import pandas as pd
from utilities import CohortDateMapper

import question_3af as q3
import question_3gh as q3_end
import question_4 as q4
import question_6 as q6



customer_df = pd.read_excel('data/customer_data.xlsx')

cdm = CohortDateMapper(customer_df)

customer_df

,cohort,user,time_year,time_month,subscription,content,genres,recency_new,bounce
0,0,0,2017,8,1,2.0,2.0,1.0000,0.5000
1,0,0,2017,9,1,1.0,1.0,1.0000,0.0000
2,0,1,2017,8,1,1.0,1.0,0.0000,1.0000
3,0,1,2017,9,1,1.0,1.0,0.0000,0.5000
4,0,2,2017,8,1,12.0,4.0,0.2500,0.0000
...,...,...,...,...,...,...,...,...,...
31672,11,20170,2018,7,1,2.0,2.0,0.5000,1.0000
31673,11,20171,2018,7,1,3.0,2.0,0.3333,0.6667
31674,11,20172,2018,7,1,1.0,1.0,1.0000,1.0000
31675,11,20173,2018,7,1,4.0,3.0,0.2500,0.0000
31676,11,20174,2018,7,1,3.0,2.0,0.0000,0.6667

In [13]:
rev_per_month_per_user = 10
discount_rate = 0.15

In [14]:
#7a clv of customer with time horizon one year
avg_retention_rates_across_cohorts = \
    q3_end.calculate_avg_retention_rates_across_cohorts(customer_df, cdm)

#replace last none with zero
avg_retention_rates_across_cohorts[-1] = 0.5
clv_dynamic = q6.calc_dynamic_clv(avg_retention_rates_across_cohorts, rev_per_month_per_user, discount_rate)
clv_dynamic_sum = clv_dynamic * 10_000
clv_dynamic_sum

151189.5060005197

In [16]:
#7d
import math

def forecast_future_retention_rates(month):
    return 0.4*(1-math.exp(-0.3*month)) + 0.5

forecasts_rr_year_2 = [forecast_future_retention_rates(month) for month in range(1, 13)]
forecasts_rr_year_2

[0.6036727117273128,
 0.6804753455623894,
 0.7373721361037603,
 0.7795223152351192,
 0.8107479359406281,
 0.8338804447113655,
 0.8510174286988073,
 0.8637128186842351,
 0.8731177949041001,
 0.8800851726528545,
 0.885246733039504,
 0.889070511021083]

In [17]:
#7f

avg_retention_rates_across_cohorts = \
    q3_end.calculate_avg_retention_rates_across_cohorts(customer_df, cdm)
avg_retention_rates_across_cohorts[-1] = 0.5
retentionrates_2_years = avg_retention_rates_across_cohorts + forecasts_rr_year_2

clv_2_years = q6.calc_dynamic_clv(retentionrates_2_years, rev_per_month_per_user, discount_rate)
clv_2_years

15.119068116317383